export const UPDATE_SEARCH_DATA = "UPDATE_SEARCH_DATA";
export const SEARCH_FLIGHTS_SUCCESS = "SEARCH_FLIGHTS_SUCCESS";
export const SEARCH_FLIGHTS_FAILURE = "SEARCH_FLIGHTS_FAILURE";
export const DISPLAY_USER_FLIGHTS = "DISPLAY_USER_FLIGHTS";
export const INSERT_USER_FLIGHTS = "INSERT_USER_FLIGHTS";
export const DELETE_USER_FLIGHTS = "DELETE_USER_FLIGHTS";